- name: configure hostname
  shell: '/bin/hostnamectl set-hostname openshift-master.campbigfalcon.io'

- name: fix hosts file 
  lineinfile:
    path: /etc/hosts
    line: '{{ ansible_default_ipv4.address }}  {{ ansible_hostname }}.{{ ansible_domain }}'  

- name: install additional repos
  yum: pkg={{ item }} state=present
  with_items:
    - epel-release
    - centos-release-openshift-origin

- name: install docker
  yum: pkg=docker state=present update_cache=yes

- name: edit docker sysconfig file
  lineinfile:
    path: /etc/sysconfig/docker
    regexp: '^OPTIONS='
    line: 'OPTIONS="--selinux-enabled --insecure-registry 172.30.0.0/16 --log-driver=journald --signature-verification=false"'

- name: start-restart docker
  service: name=docker enabled=yes state=started 

- name: install pacakges and origin-client
  yum: pkg={{ item }} state=present update_cache=yes
  with_items:
    - curl
    - git
    - net-tools
    - wget
    - origin-clients

- name: get public ip address and write to var
  command: 'curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip'
  register: public_ip

- name: start openshift cluster
  shell: "/usr/bin/oc cluster up --public-hostname={{ public_ip.stdout }} --routing-suffix={{ public_ip.stdout }}.nip.io"
