- name: set ip forward
  command: 'sysctl net.ipv4.ip_forward=1'

- name: remove old version of docker
  apt: name {{ item }} state=absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: install packages to allow apt to use repository over https
  apt: name {{ item }} state=present 
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - wget

- name: add docker official gpg key
  shell: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'

- name: setup the stable docker repository
  shell: 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'

- name: install docker
  apt: 
    name: docker-ce 
    state: present
    update_cache: yes

- name: configure docker daemon with an insecurity registry parameter
  template:
    src: files/daemon.json.j2
    dest: /etc/docker/daemon.json 
    owner: root
    group: root
    mode: 0600
  notify: restart docker 
